### ISSUE TITLE
Upstream this

### ISSUE THREAD

**Issue by roidelapluie** [benjojo/alertmanager-discord#22]
Hello,

We have lifted the moratorium on integrations in alertmanager.

Would you be willing to help us bring discord as an official native integration?

Thanks for your answer.

**Comment by benjojo** [comment]
Sure! How is best to work with the project? Feel free to redirect this convo to email (in my profile) if that helps

**Comment by roidelapluie** [comment]
I invite you to open a pull request within the alertmanager repo. We host weekly contributors office hours if you need help : https://prometheus.io/community :)

**Comment by AlexH0661** [comment]
Hello,
I was wondering if there has been any movement on this.
It would be great to see Discord webhooks natively handled in AlertManager

**Comment by benjojo** [comment]
I have made a branch to test it out. But I've been busy with other stuff
the past while. On the bright side, I have some holiday coming up, so
expect a PR "soon" :)

**Comment by AlexH0661** [comment]
Nice work :)That's fair enough!I'll keep a look out :)On 11 Jul 2021 22:14, Ben Cox ***@***.***> wrote:

I have made a branch to test it out. But I've been busy with other stuff

the past while. On the bright side, I have some holiday coming up, so

expect a PR "soon" :)

**Comment by Lusitaniae** [comment]
friendly reminder, if there's anything left to do please let us know if we can help

**Comment by benjojo** [comment]
ack, I have my WIP branch kicking around somewhere, I'll see if I can finish it in the next 2 weeks

**Comment by metalmatze** [comment]
Hey. 
In the last week I had to integrate Discord alerting for one of our projects and tried this Docker container. It didn't work so instead of further debugging the container itself, I went ahead and integrated Discord into alertmanager directly. 
This work was heavily inspired by your work on this repository.

Here's the PR: https://github.com/prometheus/alertmanager/pull/2948

**Comment by roidelapluie** [comment]
Someone has worked upstream; leading to this pull request: https://github.com/prometheus/alertmanager/pull/2948
