### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ruuda** [benjojo/alertmanager-discord#25]
First of all, thank you for this tool, it does exactly what I need!

Unfortunately, I’m not sure if I am allowed to use it in the context where I need it, I couldn’t find a license anywhere in the repository, not even a reference in the readme or a comment header in the code. From [choosealicense.com](https://choosealicense.com/no-permission/#for-users): 

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository for more details.

**Comment by benjojo** [comment]
Done

**Comment by ruuda** [comment]
That was quick, thanks :heart:
