### ISSUE TITLE
formatting issues?

### ISSUE THREAD

**Issue by Lusitaniae** [benjojo/alertmanager-discord#26]
Did discord have some update that broke formatting?

I set this up and i have a bunch of alerts that only show summary, e.g.

=== Network errors over x ===

=== Disk is full ===

For others, I can see the notification in my desktop (something something error on server x)

but the message shows empty 

![image](https://user-images.githubusercontent.com/58325/144240828-029c26ea-9f87-4c4f-87e9-838be6443cba.png)

**Comment by benjojo** [comment]
Did it used to work? Or is this a new install?

**Comment by Lusitaniae** [comment]
First time!

Now I'm thinking it could be because I'm using VictoriaMetrics VMAlert (instead of Alertmanager).

They're similar, but could have a few differences in which case no issue at all, i'm checking now

**Comment by benjojo** [comment]
Ah! Critical detail left out ;)

If possible, can you tcpdump (or obtain otherwise) what VictoriaMetrics VMAlert sends to the alertmanager-discord port?

**Comment by Lusitaniae** [comment]
new setup for me, that's why didn't come up at first 

I'll update the issue if i find something

**Comment by benjojo** [comment]
That's interesting, this fires on my system no worries.

![image](https://user-images.githubusercontent.com/1504626/144272916-ddec8ec9-1cd2-419f-b23c-5145eec51455.png)

**Comment by benjojo** [comment]
I just rebuild this from source, and replayed that payload. and it worked as well.

Are there any error messages from the program on your side? I can't see why this can't work

**Comment by Lusitaniae** [comment]
Nothing in the logs

![image](https://user-images.githubusercontent.com/58325/144276467-9797dcf2-b922-489e-9567-754744069607.png)


I'm trying local build too, same result


```
./alertmanager-discord -webhook.url https://discord.com/api/webhooks/token/token
2021/12/01 23:37:22 Listening on: 127.0.0.1:9094
2021/12/01 23:37:24 127.0.0.1:9094 - [POST] 
{"content":"","embeds":[{"title":"[FIRING:3] TXTransactionRetryCount","type":"rich","description":"","color":10038562,"fields":[{"name":"[FIRING]: TXTransactionRetryCount on 145.40.93.223","value":"The transaction retri
```

I'm new to  Discord too, could this require paid feature hah?

**Comment by Lusitaniae** [comment]
Just found it

> User Settings -> Text & Images -> Show website preview info from links pasted in chat
> 
> For some odd reason, this setting also applies to message embeds by bots too :/

**Comment by benjojo** [comment]
Cool, Glad you fixed it
