### ISSUE TITLE
Account for discord Webhook IDs with length 19

### ISSUE THREAD

**Issue by akshtshrma24** [benjojo/alertmanager-discord#30]
I recently created a webhook URL and noticed the length of the id differed from the expected 18 in [main.go:87](https://github.com/benjojo/alertmanager-discord/blob/ceceb475c7c0d5d08159e12898bfb8f6bcc66678/main.go#L87). We could change the regex to `https://discord(?:app)?.com/api/webhooks/[0-9]{18,19}/[a-zA-Z0-9_-]+`. If this looks good, im happy to open a tiny PR to resolve this.

**Comment by benjojo** [comment]
Sure, open up a PR

**Comment by akshtshrma24** [comment]
sure open pr #31

**Comment by akshtshrma24** [comment]
hey could you take a look at the pr please?

**Comment by benjojo** [comment]
Sorry about that, looks good, merged :)

**Comment by akshtshrma24** [comment]
Hey, could you update the image to include the pr? Thanks!

**Comment by benjojo** [comment]
oh god dammit DockerHub stopped doing automatic builds, Give me a moment while I figure out how to unbreak that

**Comment by benjojo** [comment]
Finally did it, that was unpleasant. Hopefully with this feature being integrated into AlertManager officially, I won't have to do that again!
