### ISSUE TITLE
Alertmanager giving POST Error

### ISSUE THREAD

**Issue by OxHimanshu** [benjojo/alertmanager-discord#38]
<img width="1433" alt="Screenshot 2022-12-19 at 1 27 19 PM" src="https://user-images.githubusercontent.com/61224737/208375404-40b32bc0-7984-428f-842d-5e29f4103aac.png">

alertmanager.yml
global:
  resolve_timeout: 5m

route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
  receiver: 'discord_webhook'
  routes:
    - matchers:
        - instance =~ "x.x.x.x:5054|x.x.x.x:6060"
      group_wait: 30s
      receiver: 'discord_webhook'
      continue: true

receivers:
- name: 'discord_webhook'
  webhook_configs:
  - url: 'http://nifty_gagarin:9094'
    send_resolved: true

**Comment by OxHimanshu** [comment]
<img width="1433" alt="Screenshot 2022-12-19 at 1 31 16 PM" src="https://user-images.githubusercontent.com/61224737/208376134-ede9de29-2c23-4b3c-acc0-ba77edae01a4.png">


While Curl localhost:9094 giving empty reply from server

**Comment by benjojo** [comment]
Server misbehaving (as seen in the screenshot) is a DNS error and so not
related to this

**Comment by OxHimanshu** [comment]
When I changed url: 'http://nifty_gagarin:9094' ----> url: 'http://localhost:9094' then also same error 
<img width="1433" alt="Screenshot 2022-12-19 at 2 13 10 PM" src="https://user-images.githubusercontent.com/61224737/208383882-2356e2e5-afc3-4290-9a94-2a9f125352c0.png">

**Comment by OxHimanshu** [comment]
Hey @benjojo, facing the issue again and again
<img width="1433" alt="Screenshot 2022-12-27 at 2 55 21 PM" src="https://user-images.githubusercontent.com/61224737/209644509-e044967a-8323-4d72-818e-cc0bef71ee67.png">

**Comment by benjojo** [comment]
What are the logs from the alertmanager-discord itself?

**Comment by OxHimanshu** [comment]
<img width="1433" alt="Screenshot 2022-12-27 at 2 58 14 PM" src="https://user-images.githubusercontent.com/61224737/209644941-800e79b3-d1ee-429c-b0b7-50a14cfbe113.png">

**Comment by benjojo** [comment]
Ah. So alertmanager-discord is running in docker but alertmanager is not.

You should consider using upgrading your alertmanager version and using the
new built in discord feature.

https://github.com/prometheus/alertmanager/pull/2948

Should be in 0.25

**Comment by OxHimanshu** [comment]
Getting the same error even after upgrading the alertmanager to 0.25
Restarted the alertmanager.service too 
 @benjojo 

<img width="1433" alt="Screenshot 2022-12-27 at 3 20 15 PM" src="https://user-images.githubusercontent.com/61224737/209648088-f9f916b9-e2b0-4956-9aa1-70225fd36742.png">
<img width="1433" alt="Screenshot 2022-12-27 at 3 21 03 PM" src="https://user-images.githubusercontent.com/61224737/209648200-8c8856c9-15d1-41fb-a8f7-3aadc2011ca1.png">

**Comment by benjojo** [comment]
No as in, with Alert Manager v0.25, there is discord support built in, no
need for alertmanager-discord!

**Comment by OxHimanshu** [comment]
fixed. Thanks a lot @benjojo
