### ISSUE TITLE
automated docker builds

### ISSUE THREAD

**Issue by intrand** [benjojo/alertmanager-discord#6]
Would you be willing to set up automated docker builds/pushes to docker hub?

I have my own local copy of the image, but it'd be nice to skip the building step and get it straight from you.

Thanks for your hard work! Getting alerts in discord is amazing! Really reduces the cost and complexity of getting alerts on mobile :)

**Comment by benjojo** [comment]
Sure, However I will be honest and say I have little idea how to do that,
could you add me ( benjojo#4972 ) so we can work on this together?

**Comment by intrand** [comment]
I totally forgot to check in on this. Better late than never? Friend request sent :)

**Comment by intrand** [comment]
This can be closed.

See https://hub.docker.com/r/benjojo/alertmanager-discord for images
